name: patchnote-to-discord

on:
  schedule:
    # default set to every 30 minutes. edit it if needed.
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - uses: actions/cache@v4
        with:
          path: last_guid.txt
          key: last-guid-${{ github.run_id }}
          restore-keys: |
            last-guid-

      - name: RSS check and send Discord Webhooks
        env:
          DISCORD_WEBHOOKS: ${{ secrets.DISCORD_WEBHOOKS }}
          STEAM_APPID: ${{ vars.STEAM_APPID }}
          DEBUG: ${{ vars.DEBUG }}
          COLOR: ${{ vars.COLOR }}
          EMBED_DESC_LIMIT:  ${{ vars.EMBED_DESC_LIMIT }}
        run: python main.py
